print('Please enter an integer value: ')
x = input()
print('Please enter another integer value: ')
y = input()
num1 = int(x)
num2 = int(y)
print(str(num1) + ' + ' + str(num2) +  ' = ' + str(num1 + num2))